name: Build
on:
  pull_request:
  push:
      branches:
      - main
jobs:
  meta-data:
    runs-on: ubuntu-latest
    steps:      
      - name: Get Source Code
        uses: actions/checkout@v2
      # print branch name
      - name: Get branch name
        id: get_branch
        shell: bash
        run: |          
          if [ ${{ github.event_name == 'pull_request' }} ]
          then
            branch=$(echo ${PR_HEAD#refs/heads/} | tr / - | tr  A-Z a-z)
            echo "::set-output name=branch::$branch"
            echo "::set-output name=namespace::$branch"
            echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"     
          elif [ ${{ github.event_name == 'push' }} ]
          then
            branch=$(echo ${PUSH_REF#refs/heads/} | tr / - | tr  A-Z a-z)
            echo "::set-output name=namespace::default"
            echo "::set-output name=branch::$branch"
            echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
          fi
  
      # extract branch name
      - name: Branch name for push
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # extract branch name on pull request
      - name: Branch name for PR
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      # extract branch name on pull request
      - name: Print branch name        
        run: |
          echo Branch name is ${{ steps.get_branch.outputs.branch }}
          echo new Branch name is ${{ steps.get_branch.outputs.BRANCH_NAME }}
          echo new Branch name is ${{ steps.extract_branch.outputs.BRANCH_NAME }}
          

   
  build:
    runs-on: ${{ matrix.os }}
    strategy:        
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Restore Dependencies
          run: npm ci
        - name: Build
          run: npm run all
