name: Build
on:
  pull_request:
  push:
      branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
        fail-fast: true
        matrix:
          os: [windoes-latest, ubuntu-latest]
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Run Action
          id: trx-parser
          uses: ./
        - name: Print Test Outcome
          run: ${{ steps.trx-parser.outputs.test-outcome }}
