name: Test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  create:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:        
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Run Action
          id: trx-parser
          uses: ./
          with:
            TRX_PATH: ${{ github.workspace }}

        - name: Print Test Outcome
          run: |
            echo Outcome is: ${{ steps.trx-parser.outputs.test-outcome }}
            echo Path is: ${{ steps.trx-parser.outputs.trx-path }}
            echo trx files: ${{ steps.trx-parser.outputs.trx-files }}
