name: Test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  create:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:        
        matrix:
          os: [windows-latest, ubuntu-latest]
    steps:
        - name: Get Source Code
          uses: actions/checkout@v2
        - name: Restore Dependencies
          run: npm ci
        - name: Build
          run: npm run all
